fixing theme bugs and cleanup
tomizechsterson/chargen-rails pull request #51
Opened 2021-06-03 22:45 UTC by dragonfaerie

@tomizechsterson Cleaned things up a fair bit, there's no more html inserted in link_to, my names aren't stellar though lol.

2021-06-04 02:23 UTC, tomizechsterson requested changes
It's looking really good. There's just a couple questions, and I think it'd be good to try camel casing for the class names, just to make things a bit easier to parse (especially with the `overridea` one.. I wasn't quite sure what was intended for that name)

2021-06-04 14:09 UTC, dragonfaerie commented on app/assets/stylesheets/users.scss
> +.specialbutton {
Fixes coming!

Sometimes a class defined in another css file will appear on the main application file in the darkmode section, to tell that class what to do in darkmode.

2021-06-04 14:11 UTC, dragonfaerie commented on app/assets/stylesheets/users.scss
> +.overridea {
Yeah, it is, it's a horrible name.  Since 3/4 of the buttons are actually "a" not buttons I made a class for those.  And then realized there were two actual "a" types that needed different styling.  Fix for this coming, I'm going to give it a better name.

2021-06-04 23:28 UTC, dragonfaerie commented on app/assets/stylesheets/users.scss
> +.specialbutton {
@tomizechsterson fixes posted!

2021-06-05 17:54 UTC, tomizechsterson approved these changes
Nice! That's a big improvement!

2021-06-05 20:19 UTC, merged